print('Isiah Task A')
print('Yi Jun Task A')
print('Diego Task A')
print('Isiah Task B')
print('Yi Jun Task B')
print('Diego Task B')
print('Isiah Task B')
print('Yi Jun Task B')
print('Diego Task B')
print('Diego Task C')